'use strict';

// The list of package publication errors.
module.exports = {
  PACKAGE_NOT_DEFINED_ERROR: 0,
  INVALID_PACKAGE_TYPE_ERROR: 1,
  COPY_ERROR: 2,
  UNLINK_ERROR: 3,
  EXTRACT_ERROR: 4,
  VALIDATION_ERROR: 5,
  CREATE_VIDEO_PUBLIC_DIR_ERROR: 6,
  SAVE_PACKAGE_DATA_ERROR: 7,
  SAVE_TIMECODE_ERROR: 8,
  MEDIA_UPLOAD_ERROR: 9,
  MEDIA_CONFIGURE_ERROR: 10,
  SCAN_FOR_IMAGES_ERROR: 10,
  CLEAN_FILE_ERROR: 12,
  CLEAN_DIRECTORY_ERROR: 13,
  PACKAGE_NOT_FOUND: 14,
  TRANSITION_ERROR: 15,
  INVALID_CONFIGURATION: 16
};
